/* This file was generated by syncqt. */
#ifndef QT_QTQMLLS_VERSION_H
#define QT_QTQMLLS_VERSION_H

#define QTQMLLS_VERSION_STR "6.6.3"

#define QTQMLLS_VERSION 0x060603

#endif // QT_QTQMLLS_VERSION_H
